version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3001
      # Database Configuration
      - DATABASE_URL=${DATABASE_URL}
      # Fallback database parameters (used if DATABASE_URL is not available)
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./packages:/app/packages
    command: ['pnpm', 'turbo', 'run', 'dev', '--filter=api']
    restart: unless-stopped
