services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: wishper_api_dev
    environment:
      # Application
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: ${API_PORT}
      API_PORT: ${API_PORT}

      # Database Configuration
      DATABASE_URL: ${DATABASE_URL}

      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}
    ports:
      - '${API_PORT}:3001'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/packages/schemas/node_modules
    command: pnpm --filter=api dev
    restart: unless-stopped
    networks:
      - wishper_dev_network

networks:
  wishper_dev_network:
    driver: bridge
