services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: wishper_api
    environment:
      # Application
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: ${API_PORT}
      API_PORT: ${API_PORT}

      # Database Configuration
      DATABASE_URL: ${DATABASE_URL}

      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}
    ports:
      - '${API_PORT}:3001'
    restart: unless-stopped
    healthcheck:
      test:
        ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3001/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - wishper_network

networks:
  wishper_network:
    driver: bridge
