version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args:
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT:-5432}
        - DB_USERNAME=${DB_USERNAME}
        - DB_DATABASE=${DB_DATABASE}
    network_mode: host
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3001
      # Database Configuration
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./packages:/app/packages
    command: ['pnpm', 'turbo', 'run', 'dev', '--filter=api']
    restart: unless-stopped
