# Nixpacks configuration for Wishper monorepo
# Nixpacks will automatically detect:
# - Node.js 20 (from engines.node in package.json)
# - pnpm (from packageManager in package.json)
# - Turborepo (from turbo.json)
# - Build and start commands (from package.json scripts)

# Environment variables for the application
[variables]
NODE_ENV = "production"
HOST = "0.0.0.0"
PORT = "3001"

# Database configuration (will be overridden by environment variables at runtime)
DB_HOST = "postgres"
DB_PORT = "5432"
DB_USERNAME = "wishper_user"
DB_DATABASE = "wishper_db"

# JWT configuration (will be overridden by environment variables at runtime)
JWT_EXPIRES_IN = "1d"
JWT_REFRESH_EXPIRES_IN = "7d"

# Tell Nixpacks to build the 'api' app from Turborepo
NIXPACKS_TURBO_APP_NAME = "api"
